name: Build Android APK (RustDesk Flutter)

on:
  workflow_dispatch:  # دستی اجرا می‌کنی

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      # کش برای سرعت بیشتر (اختیاری ولی توصیه‌شده)
      - name: Cache pub
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('flutter/pubspec.lock') }}

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('flutter/android/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Flutter pub get
        working-directory: flutter
        run: flutter pub get

      - name: Grant execute permission to gradlew
        working-directory: flutter/android
        run: chmod +x ./gradlew

      - name: Build APK (Debug)
        working-directory: flutter
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-flutter-debug
          path: flutter/build/app/outputs/flutter-apk/app-debug.apk
